### ISSUE TITLE
tensorflow version used

### ISSUE THREAD

**Issue by snowdej** [ASOS/dsf2020#1]
Hi

When I run this in colab or my own docker instance I get  syntax error

```
  File "<ipython-input-9-c352dfa2f358>", line 9
    self.user_embedding = tf.keras.layers.Embedding(len(dummy_users), ?)
                                                                      ^
SyntaxError: invalid syntax
```

Did you you a specific tensorflow version or tensorflow docker image?

**Comment by asos-gordon** [comment]
Hi @snowdej 

We used tensorflow version 2, which is now the default version in colab notebooks. 

In the tutorial which used this notebook we replaced the "?" with an integer that specified the length of the dummy_user embeddings. We used 15 in the tutorial but you can experiment with different values.
